---
version: '3.3'
services: 
  mongo_db:
    image: mongo:${MONGO_VERSION}
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    volumes:
      - mongo_data:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    environment:
      - ENV=DEV
    deploy:
      placement:
        constraints:
          - node.role == worker
      mode: replicated
      replicas: 3
      update_config:
        delay: 5s
        parallelism: 1
        failure_action: pause
      resources:
        limits:
          cpus: '0.25'
          memory: '150M'
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
    ports:
      - ${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    deploy:
      placement:
        constraints:
          - node.role == worker
      mode: replicated
      replicas: 3
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: rollback
      resources:
        limits:
          cpus: '0.30'
          memory: '300M'
      restart_policy:
        condition: on-failure
        max_attempts: 15
        delay: 1s
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    deploy:
      placement:
        constraints:
          - node.role == worker
      mode: replicated
      replicas: 3
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: rollback
      resources:
        limits:
          cpus: '0.30'
          memory: '300M'
      restart_policy:
        condition: on-failure
        max_attempts: 15
        delay: 1s
    networks:
      - back_net
      - front_net

volumes:
  mongo_data:

networks:
  front_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
  back_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
